### ISSUE TITLE
change "left" and "right" in example data...

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#494] opened 2018-08-29 19:49 UTC
...to "LastSeen" and "FirstAbsent" [a reviewer].

This is not difficult but would require checking and updating many things in data files (.csv and .rda), text (vignettes and User Guide), and screen shots.

**Comment by juniperlsimonis** [comment] 2018-09-23 11:08
closed as a duplicate of #425

**Closed by juniperlsimonis** 2018-09-23 11:08 UTC
