### ISSUE TITLE
small screens

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#524] opened 2018-09-19 05:17 UTC
from a reviewer:
"I’m using a smaller computer (13” laptop) and I select “Size Class Column” in the Analyses tab.  I can’t see below the first option so go to the right to find a slider (which only shows up when the options are available to choose and takes a few seconds to show up).  Mouse clicking on either the slider or the arrow down or up causes the option box to close instantly.  I tried more times and now occasionally when I mouse over to where the slider would be it doesn’t show up and then the option list flashing position marker freezes."

**Comment by juniperlsimonis** [comment] 2018-09-23 04:09
this is a duplicate of #447, which is closed, and #536 which i just closed
please see the comment i left in response to #447 and re-open that original issue if it's needed still

**Closed by juniperlsimonis** 2018-09-23 04:09 UTC
