### ISSUE TITLE
CP summaries

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#498] opened 2018-08-29 20:42 UTC
Use r_hat (in addition to l_hat and s_hat) as a summary statistic for persistence distributions. This requires picking a generic search interval length (Ir) and calculating ppersist(...Ir).

**Comment by ddalthorp** [comment] 2018-09-19 18:09
A nice companion statistic would be the median, which is more stable than the mean, e.g., for loglogistic distribution, the mean is not infrequently infinite because of the heavy tail but the median is much better behaved.

**Comment by ddalthorp** [comment] 2018-09-21 01:41
Once these make into the app, a short description needs to be added to the user guide as well

**Comment by juniperlsimonis** [comment] 2018-09-23 11:00
are these summary stats in the CP model output already (and just need to be pulled through the app) or do they need to be added to the CP output?

**Comment by juniperlsimonis** [comment] 2018-09-23 11:04
closing this issue specifically here as it's a duplicate of #386

**Closed by juniperlsimonis** 2018-09-23 11:04 UTC
