### ISSUE TITLE
fix k

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#270] opened 2018-06-06 15:54 UTC
Allow k to be fixed for some sizes but not necessarily for others (e.g., it might be harder to get good data for estimating k for some size classes than for others...that should not force all class models into the fixed k world but only those class models that can't otherwise be fit).

**Comment by DAPPERstats** [comment] 2018-06-07 07:38
closing as this is a duplicate of #200

**Closed by DAPPERstats** 2018-06-07 07:38 UTC
