### ISSUE TITLE
CP output

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#436] opened 2018-08-14 14:20 UTC
Show mean persistence?

"The estimates provided by this model define the distribution describing the relationship of persistence over time; however, readers of project-specific mortality monitoring reports will expect to see average persistence times with confidence intervals. Could these outputs also be generated?"

No. Persistence distributions are highly skewed, and the estimated mean persistence can strongly depend on the choice of distribution used to fit it.

**Comment by ddalthorp** [comment] 2018-08-29 11:51
but showing r for representative interval(s) would be helpful

**Comment by juniperlsimonis** [comment] 2018-09-23 11:01
closed as a duplicate of #498

**Closed by juniperlsimonis** 2018-09-23 11:01 UTC
